### ISSUE TITLE
Support for Flask 2.0+ ?

### ISSUE THREAD

**Issue by woopla** [fedora-infra/flask-healthz#9]
Hello,

When do you plan to support Flask 2.0?

Thanks,

Clément

**Comment by abompard** [comment]
Good point! The code did work with Flask 2.x unchanged, so I just updated the dependency.

**Comment by woopla** [comment]
Great, thanks for the quick fix! Any idea when the next release is?

**Comment by abompard** [comment]
I just pushed a release, thanks for the heads-up.
